1. Implement a Perceptron Algorithm to Classify a Small Dataset of Points

In [ ]:
import numpy as np

# Dataset: Points (x1, x2) and their labels (y)
X = np.array([[2, 3], [1, 1], [2, 1], [3, 4], [4, 2]])
y = np.array([1, -1, -1, 1, 1])

# Parameters
weights = np.zeros(2)  # Initialize weights
bias = 0
learning_rate = 0.1
epochs = 10

# Perceptron algorithm
for epoch in range(epochs):
    for i in range(len(X)):
        linear_output = np.dot(X[i], weights) + bias
        prediction = 1 if linear_output > 0 else -1
        error = y[i] - prediction

        # Update rule
        weights += learning_rate * error * X[i]
        bias += learning_rate * error

print(f"Weights: {weights}, Bias: {bias}")


Weights: [5.55111512e-17 2.00000000e-01], Bias: -0.4


1. Implement a perceptron algorithm to classify a small dataset of points into two categories.

In [ ]:
# prompt: Implement a perceptron algorithm to classify a small dataset of points into two categories.

import numpy as np

# Dataset: Points (x1, x2) and their labels (y)
X = np.array([[2, 3], [1, 1], [2, 1], [3, 4], [4, 2]])
y = np.array([1, -1, -1, 1, 1])

# Parameters
weights = np.zeros(2)  # Initialize weights
bias = 0
learning_rate = 0.1
epochs = 10

# Perceptron algorithm
for epoch in range(epochs):
    for i in range(len(X)):
        linear_output = np.dot(X[i], weights) + bias
        prediction = 1 if linear_output > 0 else -1
        error = y[i] - prediction

        # Update rule
        weights += learning_rate * error * X[i]
        bias += learning_rate * error

print(f"Weights: {weights}, Bias: {bias}")

# Test the trained perceptron (optional)
for i in range(len(X)):
    linear_output = np.dot(X[i], weights) + bias
    prediction = 1 if linear_output > 0 else -1
    print(f"Input: {X[i]}, True Label: {y[i]}, Prediction: {prediction}")

Weights: [5.55111512e-17 2.00000000e-01], Bias: -0.4
Input: [2 3], True Label: 1, Prediction: 1
Input: [1 1], True Label: -1, Prediction: -1
Input: [2 1], True Label: -1, Prediction: -1
Input: [3 4], True Label: 1, Prediction: 1
Input: [4 2], True Label: 1, Prediction: 1


2. Train a Simple Neural Network Using Backpropagation on MNIST

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist

# Load dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0  # Normalize

# Model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train
model.fit(X_train, y_train, epochs=5)

# Evaluate
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc}")


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8763 - loss: 0.4324
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9630 - loss: 0.1234
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - accuracy: 0.9759 - loss: 0.0790
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - accuracy: 0.9832 - loss: 0.0563
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9869 - loss: 0.0436
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9747 - loss: 0.0866
Test accuracy: 0.9765999913215637


2. Train a simple neural network using backpropagation on a dataset (e.g., MNIST) to recognize digits.

In [ ]:
# prompt: Train a simple neural network using backpropagation on a dataset (e.g., MNIST) to recognize digits.

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist

# Load dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0  # Normalize

# Model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train
model.fit(X_train, y_train, epochs=5)

# Evaluate
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_acc}")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8792 - loss: 0.4327
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.9649 - loss: 0.1188
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9769 - loss: 0.0780
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.9833 - loss: 0.0556
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9870 - loss: 0.0418
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9744 - loss: 0.0848
Test accuracy: 0.9771999716758728


3. Test the Performance of a Neural Network with Different Activations

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Create a dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2)
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Function to create a model with specified activation
def create_model(activation):
    model = Sequential([
        Dense(32, activation=activation, input_shape=(20,)),
        Dense(16, activation=activation),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

# Test each activation
activations = ['relu', 'sigmoid', 'tanh']
for act in activations:
    model = create_model(act)
    print(f"Training with {act} activation:")
    model.fit(X_train, y_train, epochs=5, verbose=0)
    _, accuracy = model.evaluate(X_test, y_test)
    print(f"Accuracy with {act}: {accuracy}")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training with relu activation:
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8710 - loss: 0.4043  
Accuracy with relu: 0.8450000286102295
Training with sigmoid activation:
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8082 - loss: 0.6312  
Accuracy with sigmoid: 0.7649999856948853
Training with tanh activation:
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9194 - loss: 0.2485  
Accuracy with tanh: 0.8999999761581421


3. Test the performance of a neural network on a dataset by comparing ReLU, Sigmoid, and Tanh activations.

In [ ]:
# prompt: Test the performance of a neural network on a dataset by comparing ReLU, Sigmoid, and Tanh activations.

# Import necessary libraries
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler # Import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


# 3. Test the Performance of a Neural Network with Different Activations

# Create a dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2)
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Function to create a model with specified activation
def create_model(activation):
    model = Sequential([
        Dense(32, activation=activation, input_shape=(20,)),
        Dense(16, activation=activation),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    return model

# Test each activation
activations = ['relu', 'sigmoid', 'tanh']
for act in activations:
    model = create_model(act)
    print(f"Training with {act} activation:")
    model.fit(X_train, y_train, epochs=5, verbose=0)
    _, accuracy = model.evaluate(X_test, y_test)
    print(f"Accuracy with {act}: {accuracy}")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training with relu activation:
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9376 - loss: 0.2442  
Accuracy with relu: 0.9200000166893005
Training with sigmoid activation:
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9429 - loss: 0.5794  
Accuracy with sigmoid: 0.949999988079071
Training with tanh activation:
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9561 - loss: 0.1941  
Accuracy with tanh: 0.9599999785423279


4. Design and Train a CNN Model to Classify a Small Dataset

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

train_images, test_images = train_images / 255.0, test_images / 255.0

model = models.Sequential([ # Added brackets here to enclose the layers
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
]) # Closing bracket for Sequential

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=10, validation_data=(test_images, test_labels))

test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"Test accuracy: {test_acc}")

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 64s 40ms/step - accuracy: 0.3302 - loss: 1.7903 - val_accuracy: 0.5413 - val_loss: 1.2661
Epoch 2/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 61s 39ms/step - accuracy: 0.5670 - loss: 1.2211 - val_accuracy: 0.6271 - val_loss: 1.0535
Epoch 3/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 82s 39ms/step - accuracy: 0.6392 - loss: 1.0171 - val_accuracy: 0.6665 - val_loss: 0.9553
Epoch 4/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 100s 50ms/step - accuracy: 0.6814 - loss: 0.9090 - val_accuracy: 0.6776 - val_loss: 0.9284
Epoch 5/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 72s 46ms/step - accuracy: 0.7075 - loss: 0.8277 - val_accuracy: 0.6791 - val_loss: 0.9454
Epoch 6/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 85s 48ms/step - accuracy: 0.7295 - loss: 0.7682 - val_accuracy: 0.6943 - val_loss: 0.8771
Epoch 7/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 84s 49ms/step - accuracy: 0.7517 - loss: 0.7012 - val_accuracy: 0.7026 - val_loss: 0.8660
Epoch 8/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 76s 45ms/step - accuracy: 0.7678 

4.  Design and train a CNN model to classify a small dataset of 10 sample images into two categories.

In [ ]:
# prompt:  Design and train a CNN model to classify a small dataset of 10 sample images into two categories.

import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

# Assuming you have 10 sample images (32x32 pixels, 3 color channels) and their labels (0 or 1)
# Replace this with your actual data loading
num_samples = 10
img_height, img_width = 32, 32
num_channels = 3

# Create dummy data for demonstration
train_images = np.random.rand(num_samples, img_height, img_width, num_channels)
train_labels = np.random.randint(0, 2, num_samples)  # 0 or 1

# Define the CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(img_height, img_width, num_channels)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',  # Use binary_crossentropy for binary classification
              metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10)



Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6000 - loss: 0.6798
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.6714
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.6445
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.6336
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6000 - loss: 0.6177
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6000 - loss: 0.5972
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6000 - loss: 0.5755
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.5506
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.5249
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6000 - loss: 0.4967


5. Develop an LSTM Model to Predict the Next Value in Fibonacci Sequence

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, LSTM, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


sentences = [
    "I love Machine Learning",
    "I love deep Learning",
    "I love NPL",

]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
total_words = len(word_index) + 1
print(word_index)

input_sequences = []
for sentence in sentences:
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

print(input_sequences)

max_sequences_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequences_len, padding='pre'))
print(input_sequences)

input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequences_len, padding='pre'))
print(input_sequences)

x = input_sequences[:, :-1]
y = input_sequences[:, -1]

y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))
print("Input shape:",x.shape)
print("Output shape:",y.shape)

{'i': 1, 'love': 2, 'learning': 3, 'machine': 4, 'deep': 5, 'npl': 6}
[[1, 2], [1, 2, 4], [1, 2, 4, 3], [1, 2], [1, 2, 5], [1, 2, 5, 3], [1, 2], [1, 2, 6]]
[[0 0 1 2]
 [0 1 2 4]
 [1 2 4 3]
 [0 0 1 2]
 [0 1 2 5]
 [1 2 5 3]
 [0 0 1 2]
 [0 1 2 6]]
[[0 0 1 2]
 [0 1 2 4]
 [1 2 4 3]
 [0 0 1 2]
 [0 1 2 5]
 [1 2 5 3]
 [0 0 1 2]
 [0 1 2 6]]
Input shape: (8, 3)
Output shape: (8, 7)


In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequences_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x, y, epochs=100, verbose=1)

def predict_next_word(seed_text):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]

    token_list = pad_sequences([token_list], maxlen=max_sequences_len-1, padding='pre')

    predicted = model.predict(token_list)
    predicted_word_index = np.argmax(predicted, axis=1)[0]

    return tokenizer.index_word.get(predicted_word_index)

seed_text = "I love"
next_word = predict_next_word(seed_text)
print(f"Next word after '{seed_text}' is: '{next_word}'")

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1250 - loss: 1.9439
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 1.9295
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6250 - loss: 1.9151
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6250 - loss: 1.9002
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6250 - loss: 1.8847
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6250 - loss: 1.8682
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6250 - loss: 1.8504
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6250 - loss: 1.8310
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6250 - loss: 1.8098
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6250 - loss: 1.7865
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6250 - loss: 1.7607
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6250 - loss

5. Develop an LSTM model to predict the next value in a small sequence of numbers (e.g., Fibonacci series)

In [ ]:
# prompt: Develop an LSTM model to predict the next value in a small sequence of numbers (e.g., Fibonacci series)

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Define the Fibonacci sequence
fibonacci_sequence = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

# Prepare the data for LSTM
sequence_length = 3  # Use the previous 3 numbers to predict the next one
X = []
y = []
for i in range(len(fibonacci_sequence) - sequence_length):
    X.append(fibonacci_sequence[i:i + sequence_length])
    y.append(fibonacci_sequence[i + sequence_length])

X = np.array(X)
y = np.array(y)

# Reshape the input data for LSTM
X = X.reshape((X.shape[0], X.shape[1], 1))

# Build the LSTM model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(sequence_length, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X, y, epochs=200, verbose=0)

# Predict the next value in the sequence
next_value = model.predict(np.array([fibonacci_sequence[-3:]])).flatten()[0]
print(f"Predicted next Fibonacci number: {next_value}")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
Predicted next Fibonacci number: 56.03984832763672


6. Compare Training Times of a Neural Network on CPU and GPU

In [ ]:
import tensorflow as tf
import time
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist

# Load dataset
(X_train, y_train), _ = mnist.load_data()
X_train = X_train / 255.0  # Normalize

# Neural network model
def create_model():
    model = Sequential([
        Flatten(input_shape=(28, 28)),
        Dense(128, activation='relu'),
        Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

# Measure training time
def measure_time(device_name):
    with tf.device(device_name):
        model = create_model()
        start_time = time.time()
        model.fit(X_train, y_train, epochs=3, verbose=0)
        end_time = time.time()
    return end_time - start_time

cpu_time = measure_time('/CPU:0')
gpu_time = measure_time('/GPU:0')  # Assumes GPU is available

print(f"CPU Training Time: {cpu_time:.2f} seconds")
print(f"GPU Training Time: {gpu_time:.2f} seconds")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


CPU Training Time: 18.42 seconds
GPU Training Time: 26.46 seconds


6. Compare the training times of a simple neural network on CPU and GPU using a provided dataset.

In [ ]:
# prompt: Compare the training times of a simple neural network on CPU and GPU using a provided dataset. using dataset

import tensorflow as tf
import time
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.datasets import mnist

# Load dataset
(X_train, y_train), _ = mnist.load_data()
X_train = X_train / 255.0  # Normalize

# Neural network model
def create_model():
    model = Sequential([
        Flatten(input_shape=(28, 28)),
        Dense(128, activation='relu'),
        Dense(10, activation='softmax')
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

# Measure training time
def measure_time(device_name):
    with tf.device(device_name):
        model = create_model()
        start_time = time.time()
        model.fit(X_train, y_train, epochs=3, verbose=0)
        end_time = time.time()
    return end_time - start_time

cpu_time = measure_time('/CPU:0')
gpu_time = measure_time('/GPU:0')  # Assumes GPU is available

print(f"CPU Training Time: {cpu_time:.2f} seconds")
print(f"GPU Training Time: {gpu_time:.2f} seconds")

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


CPU Training Time: 14.81 seconds
GPU Training Time: 15.57 seconds


7. Analyze Processing Speed Using TPU vs CPU

In [ ]:
import tensorflow as tf
import time
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Generate synthetic data
X = tf.random.normal((10000, 20))
y = tf.random.uniform((10000,), maxval=2, dtype=tf.int32)

# Simple model
def create_model():
    model = Sequential([
        Dense(64, activation='relu', input_shape=(20,)),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy')
    return model

# Measure processing time
def measure_time(device_name):
    with tf.device(device_name):
        model = create_model()
        start_time = time.time()
        model.fit(X, y, epochs=3, verbose=0)
        end_time = time.time()
    return end_time - start_time

cpu_time = measure_time('/CPU:0')
tpu_time = measure_time('/TPU:0')  # Only works in TPU-enabled environments like Colab

print(f"CPU Training Time: {cpu_time:.2f} seconds")
print(f"TPU Training Time: {tpu_time:.2f} seconds")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


CPU Training Time: 6.28 seconds
TPU Training Time: 3.02 seconds


7. Create a small dataset and analyze its processing speed using an AI accelerator (TPU) vs CPU.

In [ ]:
# prompt: Create a small dataset and analyze its processing speed using an AI accelerator (TPU) vs CPU.

import tensorflow as tf
import time

# Generate synthetic data
X = tf.random.normal((1000, 10))  # Smaller dataset
y = tf.random.uniform((1000,), maxval=2, dtype=tf.int32)

# Simple model
def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy')
    return model

# Measure processing time
def measure_time(device_name):
    with tf.device(device_name):
        model = create_model()
        start_time = time.time()
        model.fit(X, y, epochs=10, verbose=0)  # Increased epochs for better comparison
        end_time = time.time()
    return end_time - start_time

try:
    tpu_time = measure_time('/TPU:0')
    print(f"TPU Training Time: {tpu_time:.2f} seconds")
except RuntimeError as e:
    print(f"TPU not available: {e}")

cpu_time = measure_time('/CPU:0')
print(f"CPU Training Time: {cpu_time:.2f} seconds")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


TPU Training Time: 1.86 seconds
CPU Training Time: 1.48 seconds


8. Compare Adam and SGD Optimizers

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Synthetic dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train and evaluate with different optimizers
optimizers = {'Adam': 'adam', 'SGD': 'sgd'}
results = {}

for opt_name, opt in optimizers.items():
    model = Sequential([
        Dense(32, activation='relu', input_shape=(20,)),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=5, verbose=0)
    _, accuracy = model.evaluate(X_test, y_test, verbose=0)
    results[opt_name] = accuracy

print(f"Adam Accuracy: {results['Adam']:.2f}")
print(f"SGD Accuracy: {results['SGD']:.2f}")


Adam Accuracy: 0.83
SGD Accuracy: 0.74


8. Train a neural network on a synthetic dataset and compare its performance using Adam and SGD
optimizers.

In [ ]:
# prompt: Train a neural network on a synthetic dataset and compare its performance using Adam and SGD
# optimizers.

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Generate synthetic dataset
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model
def create_model(optimizer):
    model = Sequential([
        Dense(32, activation='relu', input_shape=(20,)),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Train and evaluate with Adam
model_adam = create_model('adam')
model_adam.fit(X_train, y_train, epochs=10, verbose=0) # Increased epochs for better comparison
_, accuracy_adam = model_adam.evaluate(X_test, y_test, verbose=0)

# Train and evaluate with SGD
model_sgd = create_model('sgd')
model_sgd.fit(X_train, y_train, epochs=10, verbose=0) # Increased epochs for better comparison
_, accuracy_sgd = model_sgd.evaluate(X_test, y_test, verbose=0)

print(f"Adam Accuracy: {accuracy_adam:.4f}")
print(f"SGD Accuracy: {accuracy_sgd:.4f}")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Adam Accuracy: 0.8500
SGD Accuracy: 0.7650


9. Implement a CNN for Cat vs. Dog Classification

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Dataset directory
# Replace 'path_to_cats_dogs_dataset' with the actual path to your dataset
data_dir = '/path/to/your/cats_dogs_dataset'  # Update with the correct path

# Preprocess data
datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)
train_gen = datagen.flow_from_directory(
    data_dir, target_size=(64, 64), batch_size=32, class_mode='binary', subset='training'
)
val_gen = datagen.flow_from_directory(
    data_dir, target_size=(64, 64), batch_size=32, class_mode='binary', subset='validation'
)

# CNN model
model = Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile and train
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(train_gen, validation_data=val_gen, epochs=5)

FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/cats_dogs_dataset'

9. Implement a CNN to identify whether an image dataset contains cats or dogs (binary classification).

In [ ]:
# prompt: Implement a CNN to identify whether an image dataset contains cats or dogs (binary classification).

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define image dimensions and batch size
img_width, img_height = 150, 150
batch_size = 32

# Create an ImageDataGenerator for data augmentation and preprocessing
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2  # Use 20% of data for validation
)

# Load and preprocess training data
train_generator = train_datagen.flow_from_directory(
    '/content/dogs-vs-cats',  # Replace with the actual path to your dataset
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='binary',  # Binary classification
    subset='training'
)

# Load and preprocess validation data
validation_generator = train_datagen.flow_from_directory(
    '/content/dogs-vs-cats',  # Same directory as training data
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='binary',
    subset='validation'
)

# Define the CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(img_width, img_height, 3)),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(512, activation='relu'),
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // batch_size,
    epochs=10,  # Adjust the number of epochs as needed
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // batch_size
)

FileNotFoundError: [Errno 2] No such file or directory: '/content/dogs-vs-cats'

10. Use LSTM for Text Prediction

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample text dataset
text = "hello world this is a test sentence for LSTM text prediction example"
tokens = text.split()
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1

# Create sequences
sequences = []
for i in range(1, len(tokens)):
    seq = tokens[:i+1]
    sequences.append(tokenizer.texts_to_sequences([seq])[0])

# Pad sequences
max_length = max(len(seq) for seq in sequences)
sequences = pad_sequences(sequences, maxlen=max_length, padding='pre')
X, y = sequences[:, :-1], sequences[:, -1]

# LSTM model
model = Sequential([
    Embedding(vocab_size, 10, input_length=max_length-1),
    LSTM(50),
    Dense(vocab_size, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy')

# One-hot encode the output
y = tf.keras.utils.to_categorical(y, num_classes=vocab_size)

# Train
model.fit(X, y, epochs=100, verbose=0)

# Predict next word
input_text = "hello world"
input_seq = tokenizer.texts_to_sequences([input_text])[0]
input_seq = pad_sequences([input_seq], maxlen=max_length-1, padding='pre')
predicted = np.argmax(model.predict(input_seq))
print(f"Next word: {tokenizer.index_word[predicted]}")


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step
Next word: world


10. Use LSTM to analyze a short text dataset and predict the next word in a sentence.

In [ ]:
# prompt: Use LSTM to analyze a short text dataset and predict the next word in a sentence.

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample text dataset (replace with your actual data)
sentences = [
    "I love Machine Learning",
    "I love deep Learning",
    "I love NPL",
]

# Tokenize the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
total_words = len(word_index) + 1

# Create input sequences
input_sequences = []
for sentence in sentences:
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

# Pad sequences
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

# Split into predictors and label
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

# One-hot encode the labels
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

# Define the LSTM model
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=100, verbose=1)  # Increased epochs for better training


def predict_next_word(seed_text):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list)
    predicted_word_index = np.argmax(predicted, axis=1)[0]
    return tokenizer.index_word.get(predicted_word_index)

# Example prediction
seed_text = "I love"
next_word = predict_next_word(seed_text)
print(f"Next word after '{seed_text}' is: '{next_word}'")

Epoch 1/100


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1250 - loss: 1.9459
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 1.9331
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6250 - loss: 1.9201
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6250 - loss: 1.9067
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6250 - loss: 1.8925
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6250 - loss: 1.8773
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6250 - loss: 1.8607
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6250 - loss: 1.8426
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6250 - loss: 1.8226
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6250 - loss: 1.8004
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6250 - loss: 1.7759
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6250 - loss: 1.7486
Epo